<a href="https://colab.research.google.com/github/P-RAJESWARI/Linear-Algebra/blob/main/EigenvectorsIndependent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Let the matrix be [[2,1,0]
                   [1,3,-1]
                   [0,-1,4]]

                   
Write a piece of code to calculate the eigenvalue and eigenvector of matrix A.
You may use Python functions to do calculate them.
How can you verify that the eigenvectors that correspond to distinct eigenvalues
are independent? Is there a way to code it in Python? Clue : Reduced Row
Echelon.

We find the Eigenvalues and Eigenvectors of the above matrix.If we get distinct eigen values,we have to prove that the eigenvectors that corresponds to that eigenvalues are independent vectors.For that ,we have to use Reduced Row Echolon Form (RREF),In that if the number of pivot columns matches the number of distinct eigenvalues, it suggests that the eigenvectors corresponding to distinct eigenvalues are independent.

In [10]:
#importing numpy to define the matrix as 2-Dimensional numpy array and to perform linear algebra operations such as Finding Eigen values ,Eigen vectors etc...
#importing sympy to find the RREF of the matrix and number of pivot columns
import numpy as np
import sympy

In [12]:
# Define your matrix A as 2-Dimensional numpy array
matrix = np.array([[2, 1, 0], [1, 3, -1],[0, -1, 4]])

In [13]:
# Calculate eigenvalues and eigenvectors of the given matrix
eigenvalues, eigenvectors = np.linalg.eig(matrix)

In [14]:
# Print the results
# Print Eigen values
print("Eigenvalues:")
print(eigenvalues)
# Print Eigen vectors
print("\nEigenvectors:")
print(eigenvectors)

Eigenvalues:
[1.26794919 3.         4.73205081]

Eigenvectors:
[[-0.78867513 -0.57735027 -0.21132487]
 [ 0.57735027 -0.57735027 -0.57735027]
 [ 0.21132487 -0.57735027  0.78867513]]


1.**Check if Eigenvalues are Distinct:**

We first calculate the eigenvalues of a matrix.
If all the eigenvalues are different, we say they are distinct. Otherwise, they are not distinct (meaning there are repeated eigenvalues).

2.**Form Matrix with Eigenvectors:**

For each distinct eigenvalue, we find its corresponding eigenvector(s).
We put these eigenvectors into a matrix where each column represents an eigenvector.

3.**Convert Matrix to RREF:**

We then simplify this matrix using a method called Reduced Row Echelon Form (RREF). Think of this as organizing the matrix in a special way where some rows and columns are made simpler.

4.**Check if RREF has Full Rank:**

After simplifying the matrix, we check if it has full rank. Full rank means that every column in the simplified matrix is important and none can be expressed as a combination of others.
If the number of important columns (called pivot columns) is the same as the number of distinct eigenvalues we found earlier, it means the eigenvectors corresponding to distinct eigenvalues are independent. Otherwise, they are dependent on each other.

In [9]:
# Check if eigenvalues are distinct
distinct_eigenvalues = np.unique(eigenvalues)
if len(distinct_eigenvalues) != len(eigenvalues):
    print("Eigenvalues are not distinct.")
else:
    print("Eigenvalues are distinct.")

    # Form matrix with eigenvectors corresponding to distinct eigenvalues
    eigenvectors_matrix = np.column_stack([eigenvectors[:,i] for i in range(len(eigenvalues))])

    # Convert matrix to RREF
    rref_matrix, pivot_columns = sympy.Matrix(eigenvectors_matrix).rref()

    # Check if RREF has full rank
    if len(pivot_columns) == len(distinct_eigenvalues):
        print("Eigenvectors corresponding to distinct eigenvalues are independent.")
    else:
        print("Eigenvectors corresponding to distinct eigenvalues are dependent.")

Eigenvalues are distinct.
Eigenvectors corresponding to distinct eigenvalues are independent.
